yarnPath: .yarn/releases/yarn-3.1.1.cjs

# Workaround for https://github.com/facebook/create-react-app/issues/11793
#   babel-preset-react-app tried to access
#   @babel/plugin-proposal-private-property-in-object, but it isn't declared in
#   its dependencies; this makes the require call ambiguous and unsound.
packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
